#!/bin/bash
VERSION="1.0"
NM="imx_tui"
source tui.localizer
echo $NM version $VERSION
if [ ! -f imx_usb ];then
	echo "imx_usb not found, compiling..."
	make
fi
SELECTEDBOOT=$(dialog --stdout --title "$TITLE" --menu "" 15 55 5 1 "$MAIN" 2 "$DIAGS" 3 "$FASTBOOT" 4 "$FASTBOOTSERVER")
if [ "$SELECTEDBOOT" = "1" ];then
	./imx_usb main.bin
	sleep 1
	echo Booted kindle
	dialog --msgbox "$BOOTED" 5 55
	clear
	exit 0
fi
if [ $SELECTEDBOOT = "3" ];then
	./imx_usb boot_to_builtin_fastboot.bin
	sleep 1
	echo Booted kindle
	dialog --msgbox "$BOOTED" 5 55
	clear
	exit 0
fi
if [ $SELECTEDBOOT = "2" ];then
	./imx_usb diags.bin
	sleep 1
	echo Booted kindle
	dialog --msgbox "$BOOTED" 5 55
	clear
	exit 0
fi
if [ $SELECTEDBOOT = "4" ];then
	./imx_usb fastboot.bin
	sleep 1
	echo Booted kindle
	dialog --msgbox "$BOOTED" 5 55
	clear
	exit 0
fi
clear
