#!/bin/bash
VERSION="1.0"
NM="imx_tui"
source tui.localizer
echo $NM version $VERSION
if [ ! -f imx_usb ];then
	echo "imx_usb not found, compiling..."
	make
fi
SELECTEDBOOT=$(whiptail --title "$TITLE" --menu "" 15 57 5 1 "$MAIN" 2 "$DIAGS" 3 "$FASTBOOT" 4 "$FASTBOOTSERVER" 3>&1 1>&2 2>&3)
if [ "$SELECTEDBOOT" -eq 1 ];then
	./imx_usb main.bin
	sleep 1
	echo Booted kindle
	whiptail --msgbox "$BOOTED" 7 55
	clear
	exit 0
fi
if [ "$SELECTEDBOOT" -eq 3 ];then
	./imx_usb boot_to_builtin_fastboot.bin
	sleep 1
	echo Booted kindle
	whiptail --msgbox "$BOOTED" 7 55
	clear
	exit 0
fi
if [ "$SELECTEDBOOT" -eq 2 ];then
	./imx_usb diags.bin
	sleep 1
	echo Booted kindle
	whiptail --msgbox "$BOOTED" 7 55
	clear
	exit 0
fi
if [ "$SELECTEDBOOT" -eq 4 ];then
	./imx_usb fastboot.bin
	sleep 1
	echo Booted kindle
	whiptail --msgbox "$BOOTED" 7 55
	clear
	exit 0
fi
clear
